
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: tech_eese
    password: 1234
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      authentication-database: admin
      username: chat
      password: Chat123
      host: localhost
      port: 27017
      database: chat
  main:
    allow-bean-definition-overriding: true

