server:
  port: 9004
spring:
  application:
    name: tt-chat
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
#  jpa:
#    hibernate:
#      ddl-auto: create

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL}
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm.jdbc.bind: TRACE
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
        web:
          socket: DEBUG