
spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/chat
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      authentication-database: admin
      username: chat
      password: Chat123
      host: localhost
      port: 27017
      database: chat
  main:
    allow-bean-definition-overriding: true

