spring:
  datasource:
    url: jdbc:postgresql://together-travel.c8rxjlbma4cz.ap-northeast-2.rds.amazonaws.com:5432/chat
#    url: jdbc:postgresql://localhost:5432/shop
    username: rachel
    password: smroqlgnwkd
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      host: localhost
      port: 27017
      database: chat